// Generated by CoffeeScript 1.7.1
(function() {
  var Icommand;

  Icommand = (function() {
    function Icommand() {}

    Icommand.prototype.handle = function(senter, text, args, storage, textRouter, commandManager) {
      var success;
      textRouter.output("add method to compelete this!");
      success = false;
      return success;
    };

    Icommand.prototype.help = function(commandPrefix) {
      console.log("add method to override this!");
      return [];
    };

    Icommand.prototype.hasPermission = function(sender, text, args, storage, textRouter, commandManager) {
      return true;
    };

    Icommand.prototype.handleRaw = function(sender, type, content, textRouter, commandManager) {
      return false;
    };

    return Icommand;

  })();

  module.exports = Icommand;

}).call(this);
