// Generated by CoffeeScript 1.7.1
(function() {
  var Sender;

  Sender = (function() {
    function Sender(sender, target, text, channal) {
      this.sender = sender;
      this.target = target;
      this.text = text;
      this.channal = channal;
    }

    return Sender;

  })();

  module.exports = Sender;

}).call(this);
