// Generated by CoffeeScript 1.7.1
(function() {
  var GM_Storage, fs, getFile, setFile;

  fs = require('fs');

  getFile = function(path) {
    var e;
    try {
      return fs.readFileSync(path).toString();
    } catch (_error) {
      e = _error;
      return null;
    }
  };

  setFile = function(path, content) {
    return fs.writeFileSync(path, content);
  };

  GM_Storage = (function() {
    function GM_Storage(savePath) {
      this.savePath = savePath;
      this.useQuery = true;
      this.scheduled = false;
      this.saveInterval = 600 * 1000;
      this.cache = null;
      this._load();
      process.on("exit", (function(_this) {
        return function() {
          console.log("saveing storage dump...");
          return _this._save(true);
        };
      })(this));
    }

    GM_Storage.prototype.set = function(key, value) {
      this.cache[key] = value;
      return this._save();
    };

    GM_Storage.prototype.get = function(key, defaultValue) {
      if (this.cache[key]) {
        return this.cache[key];
      } else if (defaultValue != null) {
        return defaultValue;
      } else {
        return void 0;
      }
    };

    GM_Storage.prototype.remove = function(key) {
      delete this.cache[key];
      return this._save();
    };

    GM_Storage.prototype.removeAll = function() {
      this.cache = {};
      return this._save();
    };

    GM_Storage.prototype.reload = function() {
      return this._load;
    };

    GM_Storage.prototype._load = function() {
      if (getFile(this.savePath)) {
        return this.cache = JSON.parse(getFile(this.savePath));
      } else {
        this.cache = {};
        return this._save(true);
      }
    };

    GM_Storage.prototype._save = function(noQuery) {
      var JSONText, setTimeoutR;
      setTimeoutR = function(a, b) {
        return setTimeout(b, a);
      };
      if (this.useQuery && !noQuery) {
        if (!this.scheduled) {
          setTimeoutR(this.saveInterval, (function(_this) {
            return function() {
              var JSONText;
              JSONText = JSON.stringify(_this.cache, null, 4);
              setFile(_this.savePath, JSONText);
              return _this.scheduled = false;
            };
          })(this));
          return this.scheduled = true;
        }
      } else {
        JSONText = JSON.stringify(this.cache, null, 4);
        return setFile(this.savePath, JSONText);
      }
    };

    return GM_Storage;

  })();

  module.exports = GM_Storage;

}).call(this);
