// Generated by CoffeeScript 1.7.1
(function() {
  var EventEmitter, Senter, TextRouter,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  EventEmitter = require('events').EventEmitter;

  Senter = require('./senter.js');

  TextRouter = (function(_super) {
    __extends(TextRouter, _super);

    function TextRouter() {}

    TextRouter.prototype.output = function(message, to) {
      var item, _i, _len, _results;
      if (Array.isArray(message)) {
        _results = [];
        for (_i = 0, _len = message.length; _i < _len; _i++) {
          item = message[_i];
          _results.push(this.emit("output", item, to));
        }
        return _results;
      } else {
        return this.emit("output", message, to);
      }
    };

    TextRouter.prototype.input = function(message, from, to, channal) {
      var senter;
      senter = new Senter(from, to, message, channal);
      return this.emit("input", message, senter);
    };

    return TextRouter;

  })(EventEmitter);

  module.exports = TextRouter;

}).call(this);
