// Generated by CoffeeScript 1.7.1
(function() {
  var EventEmitter, Senter, TextRouter,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  EventEmitter = require('events').EventEmitter;

  Senter = require('./senter.js');

  TextRouter = (function(_super) {
    __extends(TextRouter, _super);

    function TextRouter() {
      this.maxLength = 255;
    }

    TextRouter.prototype.output = function(message, to) {
      var index, item, result, segA, segB, _i, _len, _results;
      if (Array.isArray(message)) {
        message = message.join("\n");
      }
      message = message.split(/(?:\r\n|\n)/g);
      result = true;
      while (result) {
        result = false;
        index = 0;
        while (index < message.length) {
          if (message[index].length > this.maxLength) {
            segA = message[index].substring(0, this.maxLength);
            segB = message[index].substring(this.maxLength);
            message.splice(index, 1, segA, segB);
            result = true;
          }
          index++;
        }
      }
      _results = [];
      for (_i = 0, _len = message.length; _i < _len; _i++) {
        item = message[_i];
        _results.push(this.emit("output", item, to));
      }
      return _results;
    };

    TextRouter.prototype.input = function(message, from, to, channal) {
      var senter;
      senter = new Senter(from, to, message, channal);
      return this.emit("input", message, senter);
    };

    return TextRouter;

  })(EventEmitter);

  module.exports = TextRouter;

}).call(this);
